#!/bin/sh

icon="NAN"

bat=/sys/class/power_supply/BAT1/
per="$(cat "$bat/capacity")"

warninglock="$HOME/.cache/eww/locks/batwarn.lock"

color(){
	if [ $(cat "$bat/status") = Full ]; then
		echo "#a6e3a1"
	elif [ "$per" -le "20" ]; then
		echo "#f38ba8"
	elif [ $(cat "$bat/status") = Charging ]; then
		echo "#f9e2af"
	else
		echo "#89b4fa"
	fi
}

icon(){
	if [ $(cat "$bat/status") = Full ]; then
		echo "󱟢" && exit
	elif [ $(cat "$bat/status") = Charging ]; then
		if [ "$per" -gt "90" ]; then
			icon="󰂋"
		elif [ "$per" -gt "80" ]; then
			icon="󰂊"
		elif [ "$per" -gt "70" ]; then
			icon="󰢞"	
		elif [ "$per" -gt "60" ]; then
			icon="󰂉"
		elif [ "$per" -gt "50" ]; then
			icon="󰢝"
		elif [ "$per" -gt "40" ]; then
			icon="󰂈"
		elif [ "$per" -gt "30" ]; then
			icon="󰂇"
		elif [ "$per" -gt "20" ]; then
			icon="󰂆"
		elif [ "$per" -gt "10" ]; then
			icon="󰢜"
		elif [ "$per" -gt "0" ]; then
			icon="󰢟"
		else
			echo 󱃍 && exit
		fi
	else
		cmc
		if [ "$per" -gt "90" ]; then
			icon="󰁹"
		elif [ "$per" -gt "80" ]; then
			icon="󰂂"
		elif [ "$per" -gt "70" ]; then
			icon="󰂁"	
		elif [ "$per" -gt "60" ]; then
			icon="󰂀"
		elif [ "$per" -gt "50" ]; then
			icon="󰁿"
		elif [ "$per" -gt "40" ]; then
			icon="󰁾"
		elif [ "$per" -gt "30" ]; then
			icon="󰁽"
		elif [ "$per" -gt "20" ]; then
			icon="󰁼"
		elif [ "$per" -gt "10" ]; then
			icon="󰁻"
			sendwarning
		elif [ "$per" -gt "0" ]; then
			icon="󰁺"
			sendwarning
		else
			echo 󱃍 && exit
		fi
	fi
	echo "$icon"
}

#send warning
sendwarning(){
	if [[ ! -e $warninglock ]]; then 
		touch $warninglock
		notify-send -u critical "Battery low 󰂎" "Only $per% remaining... Connect charger"
	fi
}

#clear message cache
cmc(){
	if [ "$per" -ge "20" ] && [ -e $warninglock ]; then
		rm $warninglock
	fi
}

percent(){
	echo $per
}

state(){
	echo $(cat "$bat/status")
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
[ "$1" = "color" ] && color && exit
[ "$1" = "state" ] && state && exit
echo error
exit
